import argparse
import os
import sys
import warnings

warnings.filterwarnings("ignore", category=UserWarning, message="PySoundFile failed")
warnings.filterwarnings("ignore", category=FutureWarning, module="librosa")

from src.constants import SUPPORTED_FORMATS, VERSION
from src.processor import process_file


def main():
    parser = argparse.ArgumentParser(
        description="Generate Funscript from audio/video files via audio feature extraction."
    )
    parser.add_argument("-v", "--version", action="version",
                        version=f"NekoDancer {VERSION}")
    parser.add_argument("path", nargs="?",
                        help="Path to an audio/video file or a directory (non-recursive) "
                             "containing audio/video files.")
    parser.add_argument("-i", "--inverted", action="store_true", default=False,
                        help="Invert position mapping (default: False)")
    parser.add_argument("-l", "--license", default="Free", choices=["Free", "Paid"],
                        help='License type: "Free" or "Paid" (default: Free)')
    parser.add_argument("-t", "--title", default=None,
                        help="Title for funscript metadata; ignored when path is a directory")
    parser.add_argument("-r", "--range", type=int, default=100, choices=range(0, 101),
                        metavar="[0-100]",
                        help="Maximum position range 0-100 (default: 100)")
    parser.add_argument("--raw", action="store_true", default=False,
                        help="Output raw sawtooth curve without post-processing (simplify + offset)")
    parser.add_argument("-ma", "--multiaxis", nargs="?", const="1.0", default=None,
                        metavar="VERSION",
                        help="Generate multi-axis funscript. VERSION: 1.0 (separate files, default) or 2.0 (single file)")
    parser.add_argument("-c", "--creator", nargs="?", const="", default="NekoDancer",
                        help="Creator name for funscript metadata (default: NekoDancer)")
    parser.add_argument("-d", "--description", nargs="?", const="", default="Generated by NekoDancer.",
                        help="Description for funscript metadata (default: Generated by NekoDancer.)")

    args = parser.parse_args()

    if args.multiaxis is not None:
        v = args.multiaxis.strip()
        if v in ("2", "2.0"):
            args.multiaxis = "2.0"
        elif v in ("1", "1.0"):
            args.multiaxis = "1.0"
        else:
            print(f"Error: unsupported multiaxis version '{v}'. Use 1.0 or 2.0.", file=sys.stderr)
            sys.exit(1)

    if args.path is None:
        parser.print_help()
        sys.exit(1)

    if os.path.isfile(args.path):
        files = [args.path]
    elif os.path.isdir(args.path):
        entries = sorted(os.listdir(args.path))
        files = []
        for e in entries:
            ext = os.path.splitext(e)[1].lower()
            if ext in SUPPORTED_FORMATS:
                full = os.path.join(args.path, e)
                if os.path.isfile(full):
                    files.append(full)
        if not files:
            print("No supported audio/video files found in directory.", file=sys.stderr)
            sys.exit(1)
    else:
        print(f"Error: path '{args.path}' does not exist.", file=sys.stderr)
        sys.exit(1)

    total = len(files)
    total_dur = 0.0
    total_elapsed = 0.0
    for idx, fp in enumerate(files, 1):
        stem = os.path.splitext(os.path.basename(fp))[0]
        if total > 1:
            print(f"[{idx}/{total}] Processing: {stem}")
        else:
            print(f"Processing: {stem}")

        try:
            title_ = None if total > 1 else args.title
            dur, n_act, elapsed = process_file(fp, args.inverted, args.license, title_, args.range, args.raw, args.multiaxis, args.creator, args.description)
            total_dur += dur
            total_elapsed += elapsed
            if args.multiaxis == "1.0":
                out_name = stem + ".funscript (+ .twist/.roll/.pitch)"
            else:
                out_name = stem + ".funscript"
            rtf = elapsed / dur
            print(f"  Duration: {dur:.1f}s, Actions: {n_act}, "
                  f"Output: {out_name}, Time: {elapsed:.2f}s, RTF: {rtf:.6f}")
        except Exception as e:
            print(f"  Error: {e}", file=sys.stderr)

    if total > 1:
        total_rtf = total_elapsed / total_dur
        print(f"Summary — Duration: {total_dur:.1f}s, Time: {total_elapsed:.2f}s, RTF: {total_rtf:.6f}")


if __name__ == "__main__":
    main()
