import json
import os
import re
from datetime import date


def build_funscript(actions, inverted, license_type, title, range_val, duration, creator="NekoDancer", description="Generated by NekoDancer."):
    return {
        "inverted": inverted,
        "metadata": {
            "bookmarks": [],
            "chapters": [],
            "creator": creator,
            "description": description,
            "duration": int(duration),
            "license": license_type,
            "notes": "",
            "performers": [],
            "script_url": "",
            "tags": [],
            "title": title,
            "type": "basic",
            "video_url": ""
        },
        "range": range_val,
        "version": "1.0",
        "actions": actions,
    }


def build_funscript_axis(actions, inverted, license_type, title, range_val, duration, axis_name, creator="NekoDancer", description="Generated by NekoDancer."):
    return {
        "inverted": inverted,
        "metadata": {
            "bookmarks": [],
            "chapters": [],
            "creator": creator,
            "description": f"Axis {axis_name}. {description}",
            "duration": int(duration),
            "license": license_type,
            "notes": "",
            "performers": [],
            "script_url": "",
            "tags": [],
            "title": title,
            "type": "basic",
            "video_url": ""
        },
        "range": range_val,
        "version": "1.0",
        "actions": actions,
    }


def build_funscript_v2(l0_actions, r0_actions, r1_actions, r2_actions, duration, creator="NekoDancer", description="Generated by NekoDancer."):
    dur_int = int(duration)
    hours = dur_int // 3600
    minutes = (dur_int % 3600) // 60
    seconds = dur_int % 60
    millis = int(round((duration - dur_int) * 1000))
    duration_time = f"{hours:02d}:{minutes:02d}:{seconds:02d}.{millis:03d}"

    return {
        "metadata": {
            "duration": dur_int,
            "durationTime": duration_time,
            "topic_url": "",
            "topic_tags": [],
            "topic_creator": creator,
            "topic_description": description,
            "topic_date": date.today().isoformat()
        },
        "actions": l0_actions,
        "channels": {
            "twist": {"actions": r0_actions},
            "roll": {"actions": r1_actions},
            "pitch": {"actions": r2_actions}
        },
        "version": "2.0"
    }


def _compress_actions_json(text):
    return re.sub(
        r'("actions":\s*\[)([\s\S]*?)(\])',
        lambda m: m.group(1) + re.sub(r'\s+', '', m.group(2)) + m.group(3),
        text
    )


def _json_dumps_compact(script):
    return _compress_actions_json(json.dumps(script, indent=1, ensure_ascii=False))


def write_funscript(script, file_path):
    out_path = os.path.splitext(file_path)[0] + ".funscript"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(_json_dumps_compact(script))


def write_funscript_multiaxis_v1(file_path, l0_script, r0_script, r1_script, r2_script):
    base = os.path.splitext(file_path)[0]
    suffixes = [
        ("", l0_script),
        (".twist", r0_script),
        (".roll", r1_script),
        (".pitch", r2_script),
    ]
    for suffix, script in suffixes:
        out_path = base + suffix + ".funscript"
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(_json_dumps_compact(script))
