import os
import time

import numpy as np

from . import audio
from . import features
from . import funscript
from .constants import FRAME_SEC
from .onset import compute_global_bpm, detect_beats, regularize_beats
from .postprocess import offset_valleys_to_zero, enforce_servo_speed, stretch_to_range

# --- Tunable constants ---
_FRAME_MS = int(FRAME_SEC * 1000)
_RMS_AMP_MULT = 4
_RMS_AMP_CAP = 1.0
_PITCH_RANGE = 30.0
_TARGET_STEP_RATIO = 0.55
_ENERGY_MULT_MIN = 0.1
_ENERGY_MULT_MAX = 5.0
_CALIBRATION_ITERS = 20


def _generate_beat_actions(beats, energy_norm, centroid_norm, energy_mult, amp_scale=1.0):
    n_beats = len(beats)
    if n_beats == 0:
        return [{"at": 0, "pos": 50}]

    pitch_bias = 50.0 - _PITCH_RANGE / 2.0
    actions = [{"at": 0, "pos": 50}]

    last_time = 0.0
    for i in range(n_beats):
        mid_time = (last_time + beats[i]) / 2.0
        amplitude = energy_norm[i] * energy_mult * 50.0 * amp_scale
        offset = centroid_norm[i] * _PITCH_RANGE + pitch_bias

        pos_high = max(0.0, min(100.0, offset + amplitude))
        pos_low = max(0.0, min(100.0, offset - amplitude))

        actions.append({"at": int(round(mid_time)), "pos": int(round(pos_high))})
        actions.append({"at": int(round(beats[i])), "pos": int(round(pos_low))})
        last_time = beats[i]

    return actions


def _mean_step(actions):
    if len(actions) < 2:
        return 0.0
    total = sum(abs(actions[i]["pos"] - actions[i - 1]["pos"]) for i in range(1, len(actions)))
    return total / (len(actions) - 1)


def _calibrate_energy_mult(beats, energy_norm, centroid_norm):
    target = _TARGET_STEP_RATIO * 100.0
    lo, hi = _ENERGY_MULT_MIN, _ENERGY_MULT_MAX
    for _ in range(_CALIBRATION_ITERS):
        mid = (lo + hi) / 2.0
        actions = _generate_beat_actions(beats, energy_norm, centroid_norm, mid)
        avg_step = _mean_step(actions)
        if avg_step < target:
            lo = mid
        else:
            hi = mid
    return (lo + hi) / 2.0


def _generate_axis_actions(beats, energy_norm, centroid_norm, energy_mult,
                           amp_scale, freq_divisor, raw):
    sub_beats = beats[::freq_divisor]
    sub_energy = energy_norm[::freq_divisor]
    sub_centroid = centroid_norm[::freq_divisor]
    actions = _generate_beat_actions(sub_beats, sub_energy, sub_centroid,
                                     energy_mult, amp_scale)
    if not raw:
        actions = enforce_servo_speed(actions)
    return actions


def process_file(file_path, inverted, license_type, title, range_val, raw=False, multiaxis=None, creator="NekoDancer", description="Generated by NekoDancer."):
    t0 = time.time()

    stem = os.path.splitext(os.path.basename(file_path))[0]
    if title is None:
        title = stem

    y, sr, duration, hop_length, n_fft = audio.load_audio(file_path)
    rms_per_frame = audio.compute_rms(y, n_fft, hop_length)
    stft = audio.compute_stft_magnitude(y, n_fft, hop_length)
    n_freq_bins = n_fft // 2
    n_frames = len(rms_per_frame)

    last_freq = None
    prev_rms = 0.0
    onset_scores = []
    timestamps = []
    centroids = []

    for i in range(n_frames):
        at_ms = i * _FRAME_MS

        rms_raw = float(rms_per_frame[i])
        rms_amp = min(rms_raw * _RMS_AMP_MULT, _RMS_AMP_CAP)

        if i < stft.shape[1]:
            frame_mag = stft[:, i]
            freq_data = features.to_freq_data(frame_mag, n_freq_bins)
            cent = features.spectral_centroid(frame_mag, sr, n_fft)
        else:
            freq_data = np.zeros(n_freq_bins, dtype=np.int32)
            cent = 0.0

        centroids.append(cent)

        low_energy, low_ratio = features.low_band_features(freq_data, n_freq_bins)
        flux = features.spectral_flux(freq_data, last_freq, n_freq_bins)
        last_freq = freq_data.copy()

        sidx = i * hop_length
        eidx = min(sidx + hop_length, len(y))
        zcr = features.zero_crossing_rate(y[sidx:eidx])

        rms_rise = max(0.0, rms_amp - prev_rms)
        prev_rms = rms_amp

        score = features.onset_score(flux, low_energy, low_ratio, rms_rise, zcr)
        onset_scores.append(score)
        timestamps.append(at_ms)

    bpm = compute_global_bpm(onset_scores, timestamps)
    beats = detect_beats(onset_scores, timestamps, bpm)
    beats = regularize_beats(beats)

    n_beats = len(beats)
    energy_per_beat = np.zeros(n_beats)
    centroid_per_beat = np.zeros(n_beats)

    ts_arr = np.array(timestamps, dtype=np.float64)
    rms_arr = np.array(rms_per_frame, dtype=np.float64)
    cent_arr = np.array(centroids, dtype=np.float64)

    for i in range(n_beats):
        if i == 0:
            start_ms = beats[0] - (beats[1] - beats[0]) / 2.0 if n_beats > 1 else beats[0]
        else:
            start_ms = (beats[i - 1] + beats[i]) / 2.0
        if i == n_beats - 1:
            end_ms = beats[-1] + (beats[-1] - beats[-2]) / 2.0 if n_beats > 1 else beats[-1]
        else:
            end_ms = (beats[i] + beats[i + 1]) / 2.0

        mask = (ts_arr >= start_ms) & (ts_arr < end_ms)
        if np.any(mask):
            energy_per_beat[i] = float(np.mean(rms_arr[mask]))
            centroid_per_beat[i] = float(np.mean(cent_arr[mask]))

    e_min, e_max = float(np.min(energy_per_beat)), float(np.max(energy_per_beat))
    if e_max - e_min > 1e-10:
        energy_norm = (energy_per_beat - e_min) / (e_max - e_min)
    else:
        energy_norm = np.ones(n_beats) * 0.5

    c_min, c_max = float(np.min(centroid_per_beat)), float(np.max(centroid_per_beat))
    if c_max - c_min > 1e-10:
        centroid_norm = (centroid_per_beat - c_min) / (c_max - c_min)
    else:
        centroid_norm = np.ones(n_beats) * 0.5

    energy_mult = _calibrate_energy_mult(beats, energy_norm, centroid_norm)
    actions = _generate_beat_actions(beats, energy_norm, centroid_norm, energy_mult)

    if not raw:
        actions = offset_valleys_to_zero(actions)
        actions = enforce_servo_speed(actions)
        actions = stretch_to_range(actions)

    end_at = int(round(duration * 1000))
    if actions[-1]["at"] < end_at:
        actions.append({"at": end_at, "pos": actions[-1]["pos"]})

    if multiaxis is None:
        script = funscript.build_funscript(
            actions, inverted, license_type, title, range_val, duration, creator, description
        )
        funscript.write_funscript(script, file_path)
    else:
        r0_actions = _generate_axis_actions(
            beats, energy_norm, centroid_norm, energy_mult,
            amp_scale=0.5, freq_divisor=8, raw=raw)
        r1_actions = _generate_axis_actions(
            beats, energy_norm, centroid_norm, energy_mult,
            amp_scale=0.7, freq_divisor=4, raw=raw)
        r2_actions = _generate_axis_actions(
            beats, energy_norm, centroid_norm, energy_mult,
            amp_scale=0.5, freq_divisor=2, raw=raw)

        end_ms = int(round(duration * 1000))
        r0_actions.append({"at": end_ms, "pos": 50})
        r1_actions.append({"at": end_ms, "pos": 50})
        r2_actions.append({"at": end_ms, "pos": 50})

        if multiaxis == "1.0":
            l0_script = funscript.build_funscript(
                actions, inverted, license_type, title, range_val, duration, creator, description)
            r0_script = funscript.build_funscript_axis(
                r0_actions, inverted, license_type, title, range_val, duration, "R0", creator, description)
            r1_script = funscript.build_funscript_axis(
                r1_actions, inverted, license_type, title, range_val, duration, "R1", creator, description)
            r2_script = funscript.build_funscript_axis(
                r2_actions, inverted, license_type, title, range_val, duration, "R2", creator, description)
            funscript.write_funscript_multiaxis_v1(
                file_path, l0_script, r0_script, r1_script, r2_script)
        else:
            script = funscript.build_funscript_v2(
                actions, r0_actions, r1_actions, r2_actions, duration, creator, description)
            funscript.write_funscript(script, file_path)

    elapsed = time.time() - t0
    return duration, len(actions), elapsed
